# Titanic - model training
👋🛳️ Ahoy, welcome to Kaggle! You’re in the right place.
<a href="https://www.kaggle.com/c/titanic">Titanic kaggle problem</a>

## Import libraries

In [134]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

## Load and prepare data

In [135]:
df_train = pd.read_csv("./csv/clean-train.csv", index_col="PassengerId")
df_train.head()

Survived  Pclass  Sex       Age     SibSp     Parch      Fare  \
PassengerId                                                                  
1                   0       3    1 -0.563674  0.431350 -0.474326 -0.500240   
2                   1       1    0  0.669217  0.431350 -0.474326  0.788947   
3                   1       3    0 -0.255451 -0.475199 -0.474326 -0.486650   
4                   1       1    0  0.438050  0.431350 -0.474326  0.422861   
5                   0       3    1  0.438050 -0.475199 -0.474326 -0.484133   

             Embarked  
PassengerId            
1                   2  
2                   0  
3                   2  
4                   2  
5                   2

In [136]:
df_test = pd.read_csv("./csv/clean-test.csv", index_col="PassengerId")
df_test.head()

Pclass  Sex       Age     SibSp     Parch      Fare  Embarked
PassengerId                                                               
892               3    1  0.399522 -0.475199 -0.474326 -0.488579         1
893               3    0  1.362718  0.431350 -0.474326 -0.505273         2
894               2    1  2.518553 -0.475199 -0.474326 -0.451165         1
895               3    1 -0.178396 -0.475199 -0.474326 -0.471802         2
896               3    0 -0.563674  0.431350  0.765897 -0.398819         2

In [137]:
features = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]

In [138]:
df_train = df_train.sample(n=len(df_train))
X_train = df_train[features].to_numpy()
y_train = df_train["Survived"].to_numpy()

X_test = df_test[features].to_numpy()

In [139]:
X_train

array([[ 2.        ,  1.        , -0.87189682, ..., -0.47432585,
        -0.38447465,  2.        ],
       [ 3.        ,  1.        , -0.10133993, ..., -0.47432585,
        -0.4841333 ,  2.        ],
       [ 3.        ,  1.        , -0.10133993, ..., -0.47432585,
        -0.49059199,  1.        ],
       ...,
       [ 3.        ,  1.        , -0.10133993, ..., -0.47432585,
        -0.15999101,  1.        ],
       [ 3.        ,  0.        , -0.10133993, ..., -0.47432585,
        -0.48941823,  1.        ],
       [ 3.        ,  0.        ,  0.28393851, ..., -0.47432585,
        -0.32709542,  2.        ]], shape=(889, 7))

In [140]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,

In [141]:
X_test

array([[ 3.        ,  1.        ,  0.39952205, ..., -0.47432585,
        -0.48857868,  1.        ],
       [ 3.        ,  0.        ,  1.36271816, ..., -0.47432585,
        -0.50527302,  2.        ],
       [ 2.        ,  1.        ,  2.51855349, ..., -0.47432585,
        -0.45116541,  1.        ],
       ...,
       [ 3.        ,  1.        ,  0.7077448 , ..., -0.47432585,
        -0.50023975,  2.        ],
       [ 3.        ,  1.        , -0.10133993, ..., -0.47432585,
        -0.4841333 ,  2.        ],
       [ 3.        ,  1.        , -0.10133993, ...,  0.76589674,
        -0.19606342,  0.        ]], shape=(418, 7))

## Train ML models

### Decision tree

In [142]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

#### Save decision tree submission to csv

In [143]:
y_pred = model.predict(X_test)

df_submission = pd.DataFrame({"Survived": y_pred})
df_submission.set_index(df_test.index).to_csv("./submissions/decision-tree.csv")

### Random forest

In [144]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

#### Save decision tree submission to csv

In [145]:
y_pred = model.predict(X_test)

df_submission = pd.DataFrame({"Survived": y_pred})
df_submission.set_index(df_test.index).to_csv("./submissions/random-forest.csv")

### KNN

In [146]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(X_train, y_train)

KNeighborsClassifier()

#### Save decision tree submission to csv

In [147]:
y_pred = model.predict(X_test)

df_submission = pd.DataFrame({"Survived": y_pred})
df_submission.set_index(df_test.index).to_csv("./submissions/knn.csv")

### SVC

In [148]:
from sklearn.svm import SVC

model = SVC()
model.fit(X_train, y_train)

SVC()

#### Save decision tree submission to csv

In [149]:
y_pred = model.predict(X_test)

df_submission = pd.DataFrame({"Survived": y_pred})
df_submission.set_index(df_test.index).to_csv("./submissions/svc.csv")

### Logistic regression

In [150]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

#### Save decision tree submission to csv

In [151]:
y_pred = model.predict(X_test)

df_submission = pd.DataFrame({"Survived": y_pred})
df_submission.set_index(df_test.index).to_csv("./submissions/logistic-regression.csv")

### XGBoost classifier

In [152]:
from xgboost.sklearn import XGBClassifier

model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

#### Save decision tree submission to csv

In [153]:
y_pred = model.predict(X_test)

df_submission = pd.DataFrame({"Survived": y_pred})
df_submission.set_index(df_test.index).to_csv("./submissions/xgb-classifier.csv")

## Conclusion

We haven't tunned ML models, because we don't have the testing data grouped from training dataset. Here we have list of scores achieved by each ML model:
- decision tree: 73.4%
- random forest: 76.0%
- knn: 73.9%
- **svc**: 77.7%
- **logistic regression**: 77.0%;
- **xgboost classifier**: 77.4%;