# Titanic - model training
👋🛳️ Ahoy, welcome to Kaggle! You’re in the right place.
<a href="https://www.kaggle.com/c/titanic">Titanic kaggle problem</a>

## Import libraries

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

## Load and prepare data

In [5]:
df_train = pd.read_csv("./csv/clean-train.csv", index_col="PassengerId")
df_train.head()

Survived  Pclass  Sex       Age     SibSp     Parch      Fare  \
PassengerId                                                                  
1                   0       3    1 -0.563674  0.431350 -0.474326 -0.500240   
2                   1       1    0  0.669217  0.431350 -0.474326  0.788947   
3                   1       3    0 -0.255451 -0.475199 -0.474326 -0.486650   
4                   1       1    0  0.438050  0.431350 -0.474326  0.422861   
5                   0       3    1  0.438050 -0.475199 -0.474326 -0.484133   

             Embarked  
PassengerId            
1                   2  
2                   0  
3                   2  
4                   2  
5                   2

In [6]:
df_test = pd.read_csv("./csv/clean-test.csv", index_col="PassengerId")
df_test.head()

Pclass  Sex       Age     SibSp     Parch      Fare  Embarked
PassengerId                                                               
892               3    1  0.399522 -0.475199 -0.474326 -0.488579         1
893               3    0  1.362718  0.431350 -0.474326 -0.505273         2
894               2    1  2.518553 -0.475199 -0.474326 -0.451165         1
895               3    1 -0.178396 -0.475199 -0.474326 -0.471802         2
896               3    0 -0.563674  0.431350  0.765897 -0.398819         2

In [39]:
features = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]

In [40]:
df_train = df_train.sample(n=len(df_train))
X_train = df_train[features].to_numpy()
y_train = df_train["Survived"].to_numpy()

X_test = df_test[features].to_numpy()

In [41]:
X_train

array([[ 3.        ,  1.        , -0.94895251, ..., -0.47432585,
        -0.4718018 ,  2.        ],
       [ 3.        ,  1.        , -0.332507  , ..., -0.47432585,
        -0.28783595,  2.        ],
       [ 3.        ,  1.        , -0.10133993, ..., -0.47432585,
        -0.33414199,  1.        ],
       ...,
       [ 3.        ,  1.        , -0.02428424, ..., -0.47432585,
        -0.50435092,  2.        ],
       [ 3.        ,  0.        , -0.10133993, ..., -0.47432585,
        -0.48757203,  1.        ],
       [ 3.        ,  0.        , -0.10133993, ...,  0.76589674,
        -0.13348181,  2.        ]], shape=(889, 7))

In [42]:
y_train

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,

In [43]:
X_test

array([[ 3.        ,  1.        ,  0.39952205, ..., -0.47432585,
        -0.48857868,  1.        ],
       [ 3.        ,  0.        ,  1.36271816, ..., -0.47432585,
        -0.50527302,  2.        ],
       [ 2.        ,  1.        ,  2.51855349, ..., -0.47432585,
        -0.45116541,  1.        ],
       ...,
       [ 3.        ,  1.        ,  0.7077448 , ..., -0.47432585,
        -0.50023975,  2.        ],
       [ 3.        ,  1.        , -0.10133993, ..., -0.47432585,
        -0.4841333 ,  2.        ],
       [ 3.        ,  1.        , -0.10133993, ...,  0.76589674,
        -0.19606342,  0.        ]], shape=(417, 7))

## Train ML models

In [ ]:
models = []

### Decision tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier


### Random forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier


### KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier


### SVC

In [ ]:
from sklearn.svm import SVC


### Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression


### XGBoost classifier

In [ ]:
from xgboost.sklearn import XGBClassifier


## Evaluate ML models

## Save gender submission to csv